on:
  push:
    branches:
      - master
    paths:
      - 'Makefile'
      - 'recept.cpp'
  pull_request:
    paths:
      - 'Makefile'
      - 'recept.cpp'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: pull docker image
        run: docker pull ghcr.io/toltec-dev/toolchain:v1.3.1
      - name: Build
        run: docker run -v $(pwd):/build -w /build ghcr.io/toltec-dev/toolchain:v1.3.1 make
      - name: Save rM1
        uses: actions/upload-artifact@v3
        with:
          name: rm1
          path: build/rm1
      - name: Save rM2
        uses: actions/upload-artifact@v3
        with:
          name: rm2
          path: build/rm2
